[package]
name = "bevy-breakout"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in debug
[profile.dev]
opt-level = 1

#Enable optimizations for dependencies (incl. Bevy)
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.11.2"
